### ISSUE TITLE
HEMS

### ISSUE THREAD

**Issue by Jimbob83** [jackbayliss/Mission-Chief-Bot#14]
Hi while using the UK version of the game. If a mission requires the HEMS (Medical Helicopter) the bot will keep dispatching Ambulances, but never the HEMS.

**Comment by jackbayliss** [comment]
@Jimbob83  Unfortunately HEMS is a chance / percetage unit, at the moment the generator ignores anything with a chance purely because we're not sure if it's needed or not each time. For example : [this](https://www.missionchief.co.uk/einsaetze/147)
You'll see the corresponding json is [this](https://github.com/jackbayliss/Mission-Chief-Bot/blob/master/json/region/uk/missions/147.json) 

What I'd suggest is anything with HEMS required just add it into the relevant json's and do a pull request. 

For example the above would become :
```
{"missionId": "147", "missionName": "Spinal injury", "requirements": [{"requirement": "max. patients", "qty": "1"},{"requirement": "HEMS", "qty": "1"}]}
```

Alternatively wait for the generator to read percentages for each region no ETA at the moment.

**Comment by jackbayliss** [comment]
This is fixed with https://github.com/jackbayliss/Mission-Chief-Bot/commit/c1872ed54db3f5bd3e4b15b8b7cd1eeaf92da562 

If you get issues with them, just add it into the relevant mission and create a pull request 👍
