### ISSUE TITLE
Armed Units Personnel amount

### ISSUE THREAD

**Issue by Lew045** [jackbayliss/Mission-Chief-Bot#18]
For some of the calls the firearms units that are selected by the bot, the bot thinks they have max personnel, which is 3, however, I have set my units to have 2 in each to be a bit more realistic. Would there be an option in the config.ini to set how many officers are in each vehicle so that it will send an extra vehicle or 2 to fill in the personnel required?

**Comment by jackbayliss** [comment]
Eventually there could be; but this has to be done for each armed response unit for each region  so my answer is it’s WIP and could be for some time due to the amount of regions and vehicle ids. So I’ll need time. The more technical the bot gets the more time I need to invest. 

The more feasible answer would be just to edit each mission with the correct value so- if you had 2 per car and it needs 2 personnel it would send one. You’d then just edit the json to 1. You can easily search through all the missions using visual studio code and just search for the term “armed response personnel” and it’ll bring up each mission with them in.  

I do appreciate the suggestion and it’s something I’ve thought about. This could be in the next patch or maybe the next 3 depending on complexity.

**Comment by jackbayliss** [comment]
For reference : 
``` 
{"missionId": "176", "missionName": "Unauthorized possession of weapons", "requirements": [{"requirement": "police cars", "qty": "4"}, {"requirement": "armed response personnel", "qty": "4"}]}
```

would become:

```
{"missionId": "176", "missionName": "Unauthorized possession of weapons", "requirements": [{"requirement": "police cars", "qty": "4"}, {"requirement": "armed response vehicle (ARV)", "qty": "1"}]}
```

Closing as it's known, the player just needs to adjust it.
