### ISSUE TITLE
"ambulances was not found in the links.json - tell a developer"

### ISSUE THREAD

**Issue by sliwma** [jackbayliss/Mission-Chief-Bot#20]
I've added it, but this showed up earlier in 0.8.

**Comment by jackbayliss** [comment]
@sliwma 
The only thing I can see reference to in the PL missions is ambulanse?  This isn't in the links, but- if you see here :

https://www.operatorratunkowy.pl/einsaetze/180 for some reason the ambulanse shows here which is why it appears in the requirements, the other files dont have reference to it as we usually use Maks. Pacjenci. 

I think we can remove ambulanse in the requirements. If we are missing any vehicles you can just add them to the missions json and make a pull request.

**Comment by sliwma** [comment]
US version here, one of ARFF missions requires two ambulances.
Wilco, gonna add it later.

sob., 30 maj 2020, 14:12 użytkownik Jack <notifications@github.com> napisał:

**Comment by jackbayliss** [comment]
Ah ok! Yes I can see reference to ambulances. I'll just need to add it to the links.json. You can either make a pull request or I'll do it a little later.

Thanks again and kind regards.
