### ISSUE TITLE
Emergency doctor is not alarmed 

### ISSUE THREAD

**Issue by wombatdotcom** [jackbayliss/Mission-Chief-Bot#22]
Many open missions because of that missing vehicle (german name: NEF). 

Version: 0.0.9.2
Region: de

Happy to help furthermore.

**Comment by jackbayliss** [comment]
@wombatdotcom Thanks for creating an issue. When you say it's a 'missing vehicle' you do mean it's not despatching the mission due to the fact you don't have the vehicle? or, it's missing from the mission?

**Comment by wombatdotcom** [comment]
Almost every rescue operation requires an ambulance and an emergency doctor. The doctor is not despatched even if needed, so the mission is never completed. Vehicles are all available.

**Comment by jackbayliss** [comment]
@wombatdotcom  This sounds like it's not in the missions JSON- if you can tell me a mission name I can take a look.

**Comment by wombatdotcom** [comment]
Even in the event of a fire, this is sometimes requested. It's happening occassionally. 

Mission ID 124 "Verkehrsunfall" should be a good example. Demand probability for doctor is 50%.

**Comment by jackbayliss** [comment]
The main issue is because we don't take in the probability units so - for example:
See the JSON we have: 
```
{"missionId": "127", "missionName": "Verkehrsunfall", "requirements": [{"requirement": "streifenwagen", "qty": "2"}, {"requirement": "l\u00f6schfahrzeuge", "qty": "2"}, {"requirement": "r\u00fcstwagen", "qty": "1"}, {"requirement": "maximale patientenanzahl", "qty": "4"}]}

```

You can see that the NEF is missing, purely because we have no way to say if it's 100% needed. For now what I would suggest is adding in a NEF to the missions that require them.. Although this isn't a solution, I am hoping to change the core workings of the bot, so that we will be able to read any missing vehicles and use that.

I hope that helps.

**Comment by jackbayliss** [comment]
Closing as explained above, won't be fixed until we can understand the missing units in the alerts. Or, until you add it manually to the json.
