### ISSUE TITLE
Issues & questions

### ISSUE THREAD

**Issue by MC-bot-test** [jackbayliss/Mission-Chief-Bot#27]
Hi there
Brand newbie to this, so apologies. Firstly - great work, love the idea of automating the tedious tasks.

I wanted to try a bot to see if I could use it to automate my ARR pressing (didn’t really understand how it worked and I’ll get to that at the bottom) but I found the following things

When tested on AU server -
1 - did not dispatch any Mobile Command Vehicles as per mission requirements (I did run the update missions script first)
2 - did not despatch any TOG units (Bearcats or SUV)
3 - (noted raised previously) did not despatch any Air Ambulance although it does re-attempt to complete the mission and re-sends other vehicles
4 - If mission does not complete (eg waiting TOG or MCV etc as raised above) seems to re-dispatch ALL units, rather than just the missing ones

Just wondering if there is a work-around for any of these issues (particularly the more frequent ones like TOG and MCV)?

Secondly -  Is there any likelihood if the ability to assign personal ARR to specific missions (so the bot would read the mission name and despatch the units as per any ARR I assign to that mission name - that is, the bot automates ARR dispatch rather than mission requirement dispatch?)

Apologies if I’ve raised things already mentioned

Thanks

**Comment by jackbayliss** [comment]
The generator only generates required vehicles, so- if it’s a probability unit it won’t be on the requirements at all. This is probably where it’s not despatching units.

In terms of adding vehicles to missions it’s super easy, inside your json folder- go to region>au>missions. Id recommend downloading Visual Studio Code and opening that folder. You can then search for the mission name and add the vehicle for example add a TOG unit.

You can see an example of what I mean 
[here](https://github.com/jackbayliss/Mission-Chief-Bot/issues/14#issuecomment-632071563)

Each unit must have a “connection” in the links.json. This is so the bot knows what unit it is. To find the ID go to /api/vehicles and use the vehicle_type field.

The reason it re sends other vehicles is due to the fact the helicopter for example doesn’t exist in the requirements- so when it sees it’s not complete it’ll just retry sending the whole of the requirements- but any vehicles on scene or on route will be accounted for.

Hope that helps

**Comment by MC-bot-test** [comment]
Thank you for such a quick response.

Not fluent in any form of coding - but I’ll give it a go.

**Comment by MC-bot-test** [comment]
Sorry to be a pest
- I downloaded Visual Studio Code
- Found a mission that I wanted to add the vehicle to
- opened the links.json file
- couldn’t see the vehicle for ‘connection’ so followed your next instruction
- “find the ID go to /api/vehicles ...”
but have no idea what this refers to. Sorry I’m not sure where I look for this file

**Comment by jackbayliss** [comment]
@MC-bot-test  When I say go to /api/vehicles. I meant the URL to AU is `https://www.missionchief-australia.com/api/vehicles`.

The links.json you need to add the vehicle you're adding such as "Bike" : [vehicle_type] so, the vehicle type you get from the above URL and then you're then defining a Bike- as such.

**Comment by MC-bot-test** [comment]
Thank you for your patience. As mentioned, brand new to this.

Here is a links file for the AU server (sorry had to convert to text as wouldn't let me attach a json)
[links au text.txt](https://github.com/jackbayliss/Mission-Chief-Bot/files/4771378/links.au.text.txt)
.

TOG personnel is the biggest constraint. The only workaround I could find relatively simply was to assume all tog vehicles are staffed at max level and assign Bearcats (10 crew) or SUV (4 crew) to make (or exceed) the required personnel number.

Also missions #96, #169, #171, #172 & #173 reference "ambulance" as a requirement, yet all other missions reference "max. patient" to dispatch ambulances - so not sure if both can reference the same 'connect' vehicle ID in the links file. (I didn't test this, I just changed the to max.patients for consistency)

Thanks again !
