### ISSUE TITLE
Suggestion for EMS units

### ISSUE THREAD

**Issue by HonorAluf** [jackbayliss/Mission-Chief-Bot#35]
Is your feature request related to a problem? Please describe.
I'd like to see the mission list modified or separated to exclude Ambulance needs.

Describe the solution you'd like
I think that adding a separate list just for EMS needs would allow to bot to more smoothly dispatch Ambulances. Something along the lines of sending exact units for the correct number of patients.

"Checking EMS needs"

Then followed by

"1 out 1 patients found"
"ALS Unavailable"
"BLS Available, sending Dispatch!"

Could possibly add in IF ALS Ambulance not available check to see if BLS is and etc until it runs out of units it could possibly send to a specific call at a time. This would allow the bot to more smoothly handle Ambulance heavy missions.

I think it would work better if you made transport needs a separate line of thought for the Bot vs. all in one approach. This will help smooth the bot during the randomness of EMS needs.

Describe alternatives you've considered
I've also considered the possibility of having that code in each mission file but I feel this might cause a uptick in crashes.

**Comment by jackbayliss** [comment]
At the moment the bot only sends the full requirements.

 The upcoming release will have the ability to read missing vehicles etc, so that even if it's not in the requirement it'll be picked up by the bot. This means that ambulances will be removed from the requirements completely and then picked up by the bot when it's actually required. This, in theory should fix your issue. 

It'll be out hopefully within a week or two, I just need to test more regions. UK is fine, if you'd like to test the new release please PM me on Discord.

**Comment by jackbayliss** [comment]
As for your ALS/BLS, this should already be possible- if you set the requirement in the links.json of ambulance to be the vehicle_type of ALS and BLS it'll try and send which ever is free. If it's not already set anyway.

**Comment by jackbayliss** [comment]
[0.0.9.8](https://github.com/jackbayliss/Mission-Chief-Bot/releases/tag/0.0.9.8) has been released, please see if this aids your issue.
Missing vehicles should be picked up.

As for your more detailed logging, that's my next thing to do as long as this release is smooth.
