### ISSUE TITLE
Improvement - Specific Mission Farm

### ISSUE THREAD

**Issue by ni7roXX** [jackbayliss/Mission-Chief-Bot#40]
Hello, 

I was thinking if this could be implemented, based on the fact that the bot already knows what amount of cars is needed for a mission,  I presume that it knows what amount of cash it produces. Thus, I think that it could be nice to have a specific mission farm or above X amount credits to farm.

For example, if a mission gives more than 4k bot to ignore the mission and pass to another. 

Thoughts? 

This is useful for helping others level up and also helps the alliance more. 

Thanks
Ni7ro

**Comment by jackbayliss** [comment]
Hi Ni7ro,

Yes- it’s possible. I think first of all it would be nice to implement the credit amount per mission. So that we can feed back some information for example amount of credits earned etc. In order for the bot to ignore a mission over a certain credit limit there would have to be some kind of config option as to what the limit is.

**Comment by ni7roXX** [comment]
"In order for the bot to ignore a mission over a certain credit limit there would have to be some kind of config option as to what the limit is." 

Yup ! i thought of this as well, wanted to reply or edit the thread, and in the config to set a threshold, Ignore missions > than 4k for example. 

Thank you !
